create table transactions (
    amount numeric(38,2),
    id bigint generated by default as identity,
    receptor_id bigint,
    sender_id bigint,
    times_tamp timestamp(6),
     primary key (id)
);

create table users (
    balance numeric(38,2),
    id bigint generated by default as identity,
    email varchar(60) unique, full_name varchar(60),
    password varchar(200),
    ssn varchar(20) unique,
    user_type varchar(20) check (user_type in ('COMMON_USER','SHOPKEEPERS')),
    primary key (id)
);

alter table if exists transactions add constraint fk_transactions_receptor foreign key (receptor_id) references users;

alter table if exists transactions add constraint fk_transactions_sender foreign key (sender_id) references users;